### ISSUE TITLE
CD and DVD TableViewCell storyboard constraints problem

### ISSUE THREAD

**Issue by CristianTuretta** [CristianTuretta/mediashop#1]
In order to use the visual editor to create all the views of this project, the constraints of cd and dvd table view cell seems not work. Please @enricoGiga can you fix it? Go to the Storyboard and try to add the constraints. When we fix this issue we can start creating the structure of the db behind the app.

**Comment by enricoGiga** [comment]
Lol ok now i'm in Florece . Tomorrow evening i will do it
Il giorno sab 20 mag 2017 alle 12:22 Cristian Turetta <
notifications@github.com> ha scritto:

**Comment by CristianTuretta** [comment]
issue resolved embedding labels into stack view and then add constraints on the stack view
